[phases.setup]
nixPkgs = ["nodejs_22" "npm-9_x"]
nixLibs = ["gcc-unwrapped"]
aptPkgs = ["curl" "wget"]

[phases.install]
dependsOn = ["setup"]
cmds = ["npm ci"]
cacheDirectories = ["/root/.npm"]
paths = ["/app/node_modules/.bin"]

[phases.build]
dependsOn = ["install"]
cmds = ["npm run build"]
cacheDirectories = [".next/cache", "node_modules/.cache"]

[phases.start]
cmd = "next start -H 0.0.0.0 -p 3000"
dependsOn = []
cacheDirectories = []
paths = []